# Generated by Django 3.0.3 on 2020-02-09 19:26

from django.core.management import call_command
from django.db import models, migrations

class Migration(migrations.Migration):

    def load_data(apps, schema_editor):
        call_command("loaddata", "home/fixtures.json")

    dependencies = [
        ('home', '0002_auto_20200209_1617'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
